version: '3'

services:
  db-postgres-compose:
    image: kartoza/postgis
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASS: "postgres"
    ports:
      - "5432:5432"
    networks:
      - postgres-compose-network
      
  view-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - db-postgres-compose
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge